In [ ]:
import pandas as pd
import csv, sqlite3 
import prettytable
prettytable.DEFAULT = 'DEFAULT'

conn = sqlite3.connect("FinalDB.db")
cur = conn.cursor()

In [23]:
%load_ext sql
%sql sqlite:///FinalDB.db

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [24]:
df = pd.read_csv("../data/ChicagoCensusData.csv")
df.to_sql("CENSUS_DATA", conn, if_exists='replace', index=False, method="multi")

df2 = pd.read_csv("../data/ChicagoCrimeData.csv")
df2.to_sql("CHICAGO_CRIME_DATA", conn, if_exists='replace', index=False, method="multi")

df3 = pd.read_csv("../data/ChicagoPublicSchools.csv")
df3.to_sql("CHICAGO_PUBLIC_SCHOOLS", conn, if_exists='replace', index=False, method="multi")

566

In [ ]:
df.describe()

,COMMUNITY_AREA_NUMBER,PERCENT_OF_HOUSING_CROWDED,PERCENT_HOUSEHOLDS_BELOW_POVERTY,PERCENT_AGED_16__UNEMPLOYED,PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA,PERCENT_AGED_UNDER_18_OR_OVER_64,PER_CAPITA_INCOME,HARDSHIP_INDEX
count,77.000000,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,77.000000
mean,39.000000,4.920513,21.739744,15.341026,20.330769,35.717949,25597.000000,49.506494
std,22.371857,3.658981,11.457231,7.499497,11.746514,7.284421,15196.405541,28.690556
min,1.000000,0.300000,3.300000,4.700000,2.500000,13.500000,8201.000000,1.000000
25%,20.000000,2.325000,13.350000,9.200000,12.075000,32.150000,15804.750000,25.000000
50%,39.000000,3.850000,19.050000,13.850000,18.650000,38.050000,21668.500000,50.000000
75%,58.000000,6.800000,29.150000,20.000000,26.600000,40.500000,28715.750000,74.000000
max,77.000000,15.800000,56.500000,35.900000,54.800000,51.500000,88669.000000,98.000000

In [60]:
%sql SELECT * FROM CENSUS_DATA LIMIT 5;

 * sqlite:///FinalDB.db
Done.

[(1.0, 'Rogers Park', 7.7, 23.6, 8.7, 18.2, 27.5, 23939, 39.0),
 (2.0, 'West Ridge', 7.8, 17.2, 8.8, 20.8, 38.5, 23040, 46.0),
 (3.0, 'Uptown', 3.8, 24.0, 8.9, 11.8, 22.2, 35787, 20.0),
 (4.0, 'Lincoln Square', 3.4, 10.9, 8.2, 13.4, 25.5, 37524, 17.0),
 (5.0, 'North Center', 0.3, 7.5, 5.2, 4.5, 26.2, 57123, 6.0)]

In [58]:
%sql SELECT COMMUNITY_AREA_NAME, PERCENT_HOUSEHOLDS_BELOW_POVERTY FROM CENSUS_DATA ORDER BY PERCENT_HOUSEHOLDS_BELOW_POVERTY DESC LIMIT 5;

 * sqlite:///FinalDB.db
Done.

[('Riverdale', 56.5),
 ('Fuller Park', 51.2),
 ('Englewood', 46.6),
 ('North Lawndale', 43.1),
 ('East Garfield Park', 42.4)]

In [26]:
df2.describe()

,ID,BEAT,DISTRICT,WARD,COMMUNITY_AREA_NUMBER,X_COORDINATE,Y_COORDINATE,YEAR,LATITUDE,LONGITUDE
count,5.330000e+02,533.000000,533.000000,490.000000,490.000000,5.290000e+02,5.290000e+02,533.00000,529.000000,529.000000
mean,6.228301e+06,1187.037523,11.195122,22.608163,37.542857,1.162876e+06,1.886223e+06,2008.34334,41.843429,-87.677818
std,3.027454e+06,660.592263,6.496631,13.080119,21.409514,1.650197e+04,3.009980e+04,4.94940,0.082798,0.060073
min,2.114900e+04,111.000000,1.000000,1.000000,1.000000,1.100658e+06,1.814512e+06,2001.00000,41.645796,-87.905227
25%,3.420516e+06,711.000000,6.000000,12.000000,23.000000,1.151715e+06,1.860454e+06,2004.00000,41.772556,-87.718166
50%,6.231712e+06,1111.000000,10.000000,24.000000,30.000000,1.163235e+06,1.891447e+06,2008.00000,41.857737,-87.676733
75%,8.875058e+06,1634.000000,16.000000,32.000000,58.000000,1.174618e+06,1.907711e+06,2012.00000,41.902298,-87.634677
max,1.127717e+07,2535.000000,25.000000,50.000000,77.000000,1.204126e+06,1.951001e+06,2018.00000,42.021178,-87.528223

In [27]:
df3.describe()

,School_ID,ZIP_Code,SAFETY_SCORE,Environment_Score,Instruction_Score,Rate_of_Misconducts__per_100_students_,ISAT_Exceeding_Math__,ISAT_Exceeding_Reading__,ISAT_Value_Add_Math,ISAT_Value_Add_Read,COLLEGE_ENROLLMENT,General_Services_Route,X_COORDINATE,Y_COORDINATE,Latitude,Longitude,COMMUNITY_AREA_NUMBER,Ward,Police_District
count,566.000000,566.000000,513.000000,513.000000,513.000000,566.000000,476.000000,476.000000,468.000000,468.000000,566.000000,566.000000,5.660000e+02,5.660000e+02,566.000000,566.000000,566.000000,566.000000,566.000000
mean,609681.791519,60629.727915,49.504873,47.766082,48.288499,21.085866,20.356303,15.667017,0.068590,0.022650,626.053004,39.084806,1.163016e+06,1.885663e+06,41.841890,-87.677323,37.706714,22.060071,11.710247
std,8831.060946,20.248024,20.110837,16.215584,17.417176,27.543835,16.850870,15.208361,1.041174,1.042543,448.495105,6.165552,1.605930e+04,3.285688e+04,0.090361,0.058390,21.584135,13.645574,6.688582
min,400018.000000,60605.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,-3.500000,-5.000000,21.000000,29.000000,1.118114e+06,1.817242e+06,41.653674,-87.841052,1.000000,1.000000,1.000000
25%,609873.250000,60618.000000,35.000000,37.000000,37.000000,4.525000,9.175000,6.100000,-0.600000,-0.600000,342.250000,34.000000,1.152166e+06,1.860248e+06,41.771866,-87.717152,23.000000,10.000000,7.000000
50%,610052.500000,60625.000000,48.000000,47.000000,47.000000,12.250000,16.000000,10.950000,0.000000,0.000000,504.000000,39.000000,1.163553e+06,1.886889e+06,41.845521,-87.675878,31.500000,21.000000,10.000000
75%,610212.750000,60639.000000,61.000000,58.000000,59.000000,26.975000,24.900000,19.525000,0.700000,0.625000,790.500000,45.000000,1.174256e+06,1.911652e+06,41.913584,-87.636059,58.000000,32.750000,17.000000
max,610544.000000,60827.000000,99.000000,99.000000,99.000000,251.600000,100.000000,100.000000,3.600000,4.900000,4368.000000,49.000000,1.202811e+06,1.950960e+06,42.021064,-87.533007,77.000000,50.000000,25.000000

In [30]:
%sql SELECT * FROM CHICAGO_CRIME_DATA LIMIT 5;

 * sqlite:///FinalDB.db
Done.

[(3512276, 'HK587712', '2004-08-28', '047XX S KEDZIE AVE', '890', 'THEFT', 'FROM BUILDING', 'SMALL RETAIL STORE', 0, 0, 911, 9, 14.0, 58.0, '6', 1155838.0, 1873050.0, 2004, 41.8074405, -87.70395585, '(41.8074405, -87.703955849)'),
 (3406613, 'HK456306', '2004-06-26', '009XX N CENTRAL PARK AVE', '820', 'THEFT', '$500 AND UNDER', 'OTHER', 0, 0, 1112, 11, 27.0, 23.0, '6', 1152206.0, 1906127.0, 2004, 41.89827996, -87.71640551, '(41.898279962, -87.716405505)'),
 (8002131, 'HT233595', '2011-04-04', '043XX S WABASH AVE', '820', 'THEFT', '$500 AND UNDER', 'NURSING HOME/RETIREMENT HOME', 0, 0, 221, 2, 3.0, 38.0, '6', 1177436.0, 1876313.0, 2011, 41.81593313, -87.62464213, '(41.815933131, -87.624642127)'),
 (7903289, 'HT133522', '2010-12-30', '083XX S KINGSTON AVE', '840', 'THEFT', 'FINANCIAL ID THEFT: OVER $300', 'RESIDENCE', 0, 0, 423, 4, 7.0, 46.0, '6', 1194622.0, 1850125.0, 2010, 41.74366532, -87.56246276, '(41.743665322, -87.562462756)'),
 (10402076, 'HZ138551', '2016-02-02', '033XX W 66TH ST', '820', 'THEFT', '$500 AND UNDER', 'ALLEY', 0, 0, 831, 8, 15.0, 66.0, '6', 1155240.0, 1860661.0, 2016, 41.7734553, -87.70648047, '(41.773455295, -87.706480471)')]

In [33]:
%sql SELECT CASE_NUMBER FROM CHICAGO_CRIME_DATA WHERE DESCRIPTION LIKE '%MINOR%'

 * sqlite:///FinalDB.db
Done.

[('HL266884',), ('HK238408',)]

In [64]:
# %sql SELECT * FROM CHICAGO_PUBLIC_SCHOOLS LIMIT 5;

In [48]:
%sql SELECT AVG(SAFETY_SCORE) as SCORE, "Elementary, Middle, or High School" AS LEVEL FROM CHICAGO_PUBLIC_SCHOOLS WHERE LEVEL = "MS";

 * sqlite:///FinalDB.db
Done.

[(48.0, 'MS')]

In [66]:
%sql SELECT * from CENSUS_DATA CD JOIN CHICAGO_CRIME_DATA CCD ON CD.COMMUNITY_AREA_NUMBER = CCD.COMMUNITY_AREA_NUMBER LIMIT 5;

 * sqlite:///FinalDB.db
Done.

[(1.0, 'Rogers Park', 7.7, 23.6, 8.7, 18.2, 27.5, 23939, 39.0, 3300223, 'HK328522', '2004-04-27', '016XX W HOWARD ST', '1220', 'DECEPTIVE PRACTICE', 'THEFT OF LOST/MISLAID PROP', 'CTA PLATFORM', 1, 0, 2422, 24, 49.0, 1.0, '11', 1163750.0, 1950346.0, 2004, 42.0193833, -87.67275327, '(42.019383301, -87.67275327)'),
 (1.0, 'Rogers Park', 7.7, 23.6, 8.7, 18.2, 27.5, 23939, 39.0, 3530721, 'HK577020', '2004-08-23', '016XX W JONQUIL TER', '2024', 'NARCOTICS', 'POSS: HEROIN(WHITE)', 'SCHOOL, PUBLIC, GROUNDS', 1, 0, 2422, 24, 49.0, 1.0, '18', 1163893.0, 1951001.0, 2004, 42.0211776, -87.67220843, '(42.021177601, -87.67220843)'),
 (1.0, 'Rogers Park', 7.7, 23.6, 8.7, 18.2, 27.5, 23939, 39.0, 4646705, 'HM244120', '2006-03-21', '016XX W TOUHY AVE', '1320', 'CRIMINAL DAMAGE', 'TO VEHICLE', 'STREET', 0, 0, 2423, 24, 49.0, 1.0, '14', 1164202.0, 1947913.0, 2006, 42.01269752, -87.67115923, '(42.012697523, -87.671159228)'),
 (1.0, 'Rogers Park', 7.7, 23.6, 8.7, 18.2, 27.5, 23939, 39.0, 4750131, 'HM360756', '2006-05-19', '071XX N PAULINA ST', '2820', 'OTHER OFFENSE', 'TELEPHONE THREAT', 'RESIDENCE', 0, 1, 2423, 24, 49.0, 1.0, '26', 1163884.0, 1947582.0, 2006, 42.011796, -87.67233871, '(42.011795997, -87.67233871)'),
 (1.0, 'Rogers Park', 7.7, 23.6, 8.7, 18.2, 27.5, 23939, 39.0, 5784844, 'HN595319', '2007-09-17', '070XX N CLARK ST', '1506', 'PROSTITUTION', 'SOLICIT ON PUBLIC WAY', 'SIDEWALK', 1, 0, 2424, 24, 49.0, 1.0, '16', 1163398.0, 1946852.0, 2007, 42.00980315, -87.6741476, '(42.009803145, -87.6741476)')]

In [ ]:
%sql SELECT COMMUNITY_AREA_NUMBER, COUNT(COMMUNITY_AREA_NUMBER) FROM CHICAGO_CRIME_DATA GROUP BY COMMUNITY_AREA_NUMBER ORDER BY COMMUNITY_AREA_NUMBER DESC LIMIT 5;

 * sqlite:///FinalDB.db
Done.

[(77.0, 2), (76.0, 4), (75.0, 1), (73.0, 3), (72.0, 4)]